[build-system]
requires = ["hatchling", "hatch-fancy-pypi-readme"]
build-backend = "hatchling.build"

[project]
name = "cumulusci-azure-devops"
version = "0.1.0"
description = "An plugin for cumulusci supporting Azure DevOps"
authors = [{name = "Rupesh J"}]
dependencies = [
    "cumulusci>=4.3.0.dev0",
    "azure-devops",
    "requests",
    "humanfriendly",
    "distro"
]
requires-python = ">=3.11"

[project.entry-points."cumulusci.plugins"]
azure_devops = "cumulusci_ado.azure_devops:AzureDevOpsPlugin"

[tool.hatch.build]
include = [
    "/cumulusci_ado",
    '/cumulusci_ado/**/*.*', # y[a]ml, js[on], etc.
]
[tool.hatch.build.targets.sdist]
include = [
    "/cumulusci_ado",
    '/cumulusci_ado/**/*.*', # y[a]ml, js[on], etc.
]
[tool.hatch.build.targets.wheel]
exclude = ["*.sql", "*.zip"]

[tool.pyright]
reportMissingImports = "none"
typeCheckingMode = "basic"
exclude = ["**/test_*", "**/tests/**"]
# Add files to this list as you make them compatible.
include = [
    "**/*.py",  # Include all Python files
]