name: Feature Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install lint dependencies
        run: pip install .[lint]
      - name: Run pre-commit
        run: pre-commit run --all-files

  test:
    name: Unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install test dependencies
        run: pip install .[dev]
      - name: Run tests
        run: pytest --cov=cumulusci_ado

  docs:
    name: Build Docs
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install doc dependencies
        run: pip install .[docs]
      - name: Build Docs
        run: |
          if [ -d docs ]; then
            sphinx-build -b html docs docs/_build
          else
            echo "No docs directory, skipping."
          fi
